name: pkillxx
version: '1.0'
summary: pkillxx
description: |
OfflineIMAP is software that downloads […]

confinement: devmode
base: core18

parts:
offlineimap:
  plugin: python
  python-version: python2
  source: https://github.com/snapcraft-docs/offlineimap.git
  stage-packages:
    - python-six

apps:
offlineimap:
  command: bin/offlineimap
