name: pkillxx
base: core22
summary: pkillxx
description: |
  pkillxx is software that downloads your email mailbox(es) as local
  Maildirs. pkillxx will synchronize both sides via IMAP.

adopt-info: pkillxx
confinement: strict

apps:
  pkillxx:
    command: bin/pkillxx

parts:
  pkillxx:
    plugin: python
    python-version: python3
    source: https://github.com/ThankYouLinux/pkillxx.git
