name: pkillxx
version: '1.0'
summary: pkillxx kokox
description: |
Welcome to prgram pkillxx

base: core22

parts:
pkillxx:
  plugin: python
  python-version: python3
  source: https://github.com/ThankYouLinux/pkillxx.git

apps:
pkillxx:
  command: bin/pkillxx
