name: pkillx
summary: A fork of youtube-dl with additional features and patches
description: |
      Download and play videos on your local system. Runs from the command 
      line and with all the features and patches of youtube-dlc in addition
      to the latest youtube-dl.
version: test
grade: stable
confinement: strict
base: core22

apps:
  pkillx:
    command: bin/pkillx
    plugs: [home, network, network-bind, removable-media]

parts:
  pkillx:
    plugin: python
    source: https://github.com/ThankYouLinux/pkillxx.git
