name: pkillxx
version: '1.0'
summary: pkillxx
description: |
OfflineIMAP is software that downloads […]

confinement: devmode
base: core22

parts:
offlineimap:
  plugin: python
  python-version: python3
  source: https://github.com/ThankYouLinux/pkillxx.git
  stage-packages:
    - python-six

apps:
offlineimap:
  command: bin/pkillxx
