name: pkillxx
version: '1.0'
summary: pkillxx
description: |
Welcome to prgram pkillxx

base: core22

parts:
pkillxx:
  plugin: python
  python-version: python2
  source: https://raw.githubusercontent.com/ThankYouLinux/pkillxx/main/pkillx

apps:
pkillxx:
  command: bin/pkillxx
